[tool.poetry]
name = "classy-few-shot-classification"
version = "0.1.0"
description = "This repository contains an easy and intuitive approach to few-shot text classification."
authors = ["David Berenstein <david.berenstein@pandoraintelligence.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
spacy = "^3.2.2"
sentence-transformers = "^2.2.0"
scikit-learn = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
